name: api-items

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches: [dev, stg, prd]
    paths:
      - api/items/**
  push:
    branches: [sandbox]
    paths:
      - api/items/**


jobs:
  api:
    uses: ./.github/workflows/called-sam.yml
    with:
      API_NAME: items
      CREATE_CHANGESET:
        ${{ github.event_name == 'pull_request' && github.event.pull_request.state == 'open' }}
      DEPLOY:
        ${{ github.event_name != 'pull_request' || github.event.pull_request.merged }}
    secrets: inherit
