AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket and Access Policy.

# Metadata:
#   AWS::CloudFormation::Interface:
#     ParameterGroups:
#       - Label:
#           default: General settings
#         Parameters:
#           - StageName


Parameters:
  Param:
    Type: String
    Default: param
  StageName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stg
      - prd
    Description: dev, stg, prd

Resources:
  TestRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal: "*"
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
                token.actions.githubusercontent.com:sub: !Sub repo:${Param}/${StageName}


