AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket and Access Policy.

Parameters:
  Param:
    Type: String
    Default: param3
  StageName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stg
      - prd
    Description: dev, stg, prd

Resources:
  TestRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              AWS:
                - !Sub "arn:aws:iam::696169161957:root"
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
                token.actions.githubusercontent.com:sub: !Sub repo:${Param}/${StageName}


