version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "DroneEC-items-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1pc4p5qfuxlsn"
s3_prefix = "DroneEC-items-dev"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ServiceName=\"DroneEC\" Version=\"v1\" StageName=\"dev\" ResourceName=\"items\" UseGetMethod=\"Y\" UsePostMethod=\"N\" UsePutMethod=\"N\" UseDeleteMethod=\"N\" PartitionKeyName=\"itemId\" PartitionKeyType=\"S\" SortKeyName=\"\" SortKeyType=\"S\" StreamViewType=\"\" CognitoArn=\"arn:aws:cognito-idp:ap-northeast-1:994983803536:userpool/ap-northeast-1_M5I3Hz90H\""
image_repositories = []
confirm_changeset = true
