name: test trigger
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  echo_event_name:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.ref_name }}
      - run: echo ${{ github.event.pull_request.base.ref }}
      - run: echo ${{ github.event.pull_request.base.ref || github.event_name }}
      - run: echo ${{ github.event_name == 'push' && 'event_name is push' }}
      - run: echo ${{ (github.event_name == 'push' && 'event_name is push') || (github.event_name == 'workflow_dispatch' && 'event_name is workflow_dispatch') }}
      - run: echo ${{ (github.event_name == 'push' && 'event_name is push') || (github.event_name == 'pull_request' && 'event_name is pull_request') }}
      - run: echo ${{ (github.event_name == 'pull_request' && 'event_name is pull_request') || '' }}
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
      - name: Comment on Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `Hello world!
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: multiline
        uses: actions/github-script@v6
        with:
          script: |
            const x = 'abc def' + 'zzz';
            console.log(x);

      - name: multiline
        uses: actions/github-script@v6
        with:
          script: |
            const x = 'abc def'
             + 'zzz';
            console.log(x);

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo The PR was merged
