name: test trigger
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  echo_event_name:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.ref_name }}
      - run: echo ${{ github.event.pull_request.base.ref }}

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo The PR was merged
