name: test trigger
on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - closed

jobs:
  echo_event_name:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event_name }}

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo The PR was merged
