name: AWS credentials test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - run: echo ${{ github.ref_name }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::455968754607:role/GitHubActionsRole
          aws-region: ap-northeast-1
      - run: aws sts get-caller-identity