name: Called SAM

on:
  workflow_call:
    inputs:
      CREATE_CHANGESET:
        required: false
        type: boolean
        default: false
      DEPLOY:
        required: false
        type: boolean
        default: false

      API_NAME:
        required: true
        type: string
      COGNITO_USER_POOL:
        required: true
        type: string
        description: user | shop
      ADDITIONAL_PARAMETERS:
        required: false
        type: string
        default: ''
        
      AWS_REGION:
        required: false
        type: string
        default: ap-northeast-1
      SAM_CAPABILITIES:
        required: false
        type: string
        default: CAPABILITY_IAM
      PYTHON_VERSION:
        required: false
        type: string
        default: '3.9'

    secrets:
      ACTION_ROLE:
        required: true
      DEPLOY_ROLE:
        required: true
      TEMPLATE_BUCKET:
        required: true
      COGNITO_ARN_USER:
        required: true
      COGNITO_ARN_SHOP:
        required: true
      AWS_ACCOUNT_ID:
        required: true


env:
  STACK_NAME_PREFIX: cicd-api-
  PARAMETER_FILE: parameters.txt


permissions: 
  contents: read
  id-token: write
  pull-requests: write


jobs:
  deploy:
    runs-on: ubuntu-latest
    if: inputs.CREATE_CHANGESET || inputs.DEPLOY
    timeout-minutes: 20
    environment:
      name: ${{ github.event.pull_request.base.ref || github.ref_name }}
    env:
      STAGE_NAME: ${{ github.event.pull_request.base.ref || github.ref_name }}
      COGNITO_ARN: >-
        ${{ 
          (inputs.COGNITO_USER_POOL == 'user' && secrets.COGNITO_ARN_USER) || 
          (inputs.COGNITO_USER_POOL == 'shop' && secrets.COGNITO_ARN_SHOP) ||
          ''
        }}
    defaults:
      run:
        working-directory: api/${{ inputs.API_NAME }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ACTION_ROLE }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: cli version & id
        run: |-
          aws --version
          sam --version
          aws sts get-caller-identity

      - name: sam build
        run: sam build --use-container

      # Create & show changeset
      - name: create changeset
        if: inputs.CREATE_CHANGESET
        id: create_changeset
        run: |-
          sam deploy \
            --no-execute-changeset \
            --no-fail-on-empty-changeset \
            --no-disable-rollback \
            --role-arn ${{ secrets.DEPLOY_ROLE }} \
            --s3-bucket ${{ secrets.TEMPLATE_BUCKET }} \
            --s3-prefix "${{ secrets.AWS_ACCOUNT_ID }}/${{ env.STACK_NAME_PREFIX }}${{ inputs.API_NAME }}-${{ env.STAGE_NAME}}" \
            --stack-name "${{ env.STACK_NAME_PREFIX }}${{ inputs.API_NAME }}" \
            --capabilities ${{ inputs.SAM_CAPABILITIES }} \
            --parameter-overrides `cat ${{ env.PARAMETER_FILE }} | \
              sed -E 's@^(StageName=).*$@\1"${{ env.STAGE_NAME }}"@g' | \
              sed -E 's@^(LambdaRuntime=).*$@\1"python${{ inputs.PYTHON_VERSION }}"@g' | \
              sed -E 's@^(CognitoArn=).*$@\1"${{ env.COGNITO_ARN }}"@g'` \
              ${{ inputs.ADDITIONAL_PARAMETERS }} \
            > result.txt
      
      - name: show create-changeset result
        if: inputs.CREATE_CHANGESET
        continue-on-error: true
        run: |-
          cat result.txt

      - name: store create-changeset result
        if: inputs.CREATE_CHANGESET && steps.create_changeset.outcome == 'success'
        run: |-
          echo "CHANGESET_TABLE<<EOF" >> $GITHUB_ENV
          cat result.txt | sed -z 's@.*CloudFormation stack changeset\n\(.*\)\nChangeset created.*@\1@g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment on Pull Request
        uses: actions/github-script@v6
        if: inputs.CREATE_CHANGESET && github.event_name == 'pull_request' && env.CHANGESET_TABLE
        with:
          script: |
            const output = `## ${{ env.STACK_NAME_PREFIX }}${{ inputs.API_NAME }} changeset
            \`\`\`
            ${{ env.CHANGESET_TABLE }}
            \`\`\`
            *Pusher: @${{ github.actor }}*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: store create-changeset result
        if: inputs.CREATE_CHANGESET && steps.create_changeset.outcome == 'success'
        run: |-
          echo "CHANGESET_ARN<<EOF" >> $GITHUB_ENV
          cat result.txt | sed -z 's@.*\(arn:aws:cloudformation:\).*@\1@g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: describe changeset
        if: inputs.CREATE_CHANGESET && github.event_name == 'pull_request' && env.CHANGESET_ARN
        run: |-
          echo "CHANGESET_DESCRIPTION<<EOF" >> $GITHUB_ENV
          aws cloudformation describe-change-set \
            --change-set-name ${{ env.CHANGESET_ARN }} \
            | jq '.Changes[].ResourceChange | {Operation: .Action, LogicalId: .LogicalResourceId, Type: .ResourceType, Replacement: .Replacement}' \
            >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment on Pull Request
        uses: actions/github-script@v6
        if: inputs.CREATE_CHANGESET && github.event_name == 'pull_request' && env.CHANGESET_DESCRIPTION
        with:
          script: |
            const output = `## ${{ env.STACK_NAME_PREFIX }}${{ inputs.API_NAME }} changeset
            \`\`\`
            ${{ env.CHANGESET_DESCRIPTION }}
            \`\`\`
            *Pusher: @${{ github.actor }}*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      # Deploy
      - name: sam deploy
        if: inputs.DEPLOY
        run: |-
          sam deploy \
            --no-confirm-changeset --force-upload \
            --no-fail-on-empty-changeset \
            --no-disable-rollback \
            --role-arn ${{ secrets.DEPLOY_ROLE }} \
            --s3-bucket ${{ secrets.TEMPLATE_BUCKET }} \
            --s3-prefix "${{ secrets.AWS_ACCOUNT_ID }}/${{ env.STACK_NAME_PREFIX }}${{ inputs.API_NAME }}-${{ env.STAGE_NAME}}" \
            --stack-name "${{ env.STACK_NAME_PREFIX }}${{ inputs.API_NAME }}" \
            --capabilities ${{ inputs.SAM_CAPABILITIES }} \
            --parameter-overrides `cat ${{ env.PARAMETER_FILE }} | \
              sed -E 's@^(StageName=).*$@\1"${{ env.STAGE_NAME }}"@g' | \
              sed -E 's@^(LambdaRuntime=).*$@\1"python${{ inputs.PYTHON_VERSION }}"@g' | \
              sed -E 's@^(CognitoArn=).*$@\1"${{ env.COGNITO_ARN }}"@g'` \
              ${{ inputs.ADDITIONAL_PARAMETERS }}
