name: Called CloudFormation

on:
  workflow_call:
    inputs:
      CREATE_CHANGESET:
        required: false
        type: boolean
        default: false
      DEPLOY:
        required: false
        type: boolean
        default: false
      STACK_NAME:
        required: true
        type: string
      TEMPLATE_FILE_NAME:
        required: false
        type: string
        default: template.yml
      WORKING_DIRECTORY:
        required: true
        type: string
      AWS_REGION:
        required: false
        type: string
        default: ap-northeast-1
      SAM_CAPABILITIES:
        required: false
        type: string
        default: CAPABILITY_IAM
    secrets:
      ACTION_ROLE:
        required: true
      DEPLOY_ROLE:
        required: true
      TEMPLATE_BUCKET:
        required: true
      AWS_ACCOUNT_ID:
        required: true


env:
  STACK_NAME_PREFIX: cicd-cfn-


permissions:
  id-token: write
  contents: read

jobs:
  CloudFormation:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: ${{ github.event.pull_request.base.ref || github.ref_name }}
    env:
      STAGE_NAME: ${{ github.event.pull_request.base.ref || github.ref_name }}
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ACTION_ROLE }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: cli version & id
        run: |-
          aws --version
          aws sts get-caller-identity

      - name: create changeset
        if: inputs.CREATE_CHANGESET
        run: |-
          echo "CHANGESET<<EOF" >> $GITHUB_ENV
          aws cloudformation deploy \
            --no-execute-changeset \
            --no-fail-on-empty-changeset \
            --template-file ${{ inputs.TEMPLATE_FILE_NAME }} \
            --role-arn ${{ secrets.DEPLOY_ROLE }} \
            --s3-bucket ${{ secrets.TEMPLATE_BUCKET }} \
            --s3-prefix "${{ secrets.AWS_ACCOUNT_ID }}/${{ env.STACK_NAME_PREFIX }}${{ inputs.STACK_NAME }}-${{ env.STAGE_NAME }}" \
            --stack-name "${{ env.STACK_NAME_PREFIX }}${{ inputs.STACK_NAME }}" \
            --capabilities ${{ inputs.SAM_CAPABILITIES }} \
            --parameter-overrides StageName=${{ env.STAGE_NAME }} \
            | tee -a $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: show changeset (passed if empty changeset)
        if: inputs.CREATE_CHANGESET && env.CHANGESET == '*arn:aws:*'
        run: |-
          aws cloudformation describe-change-set \
            --change-set-name `echo "${{ env.CHANGESET }}" | sed -z 's@.*arn:aws:@arn:aws:@g'` \
            | jq ".Changes"

      # - name: store create-changeset result
      #   if: inputs.CREATE_CHANGESET && steps.create_changeset.outcome == 'success'
      #   run: |-
      #     cat result.txt | sed -z 's@.*\(arn:aws:cloudformation:[^ \n$]*\)@CHANGESET_ARN=\1@g' >> $GITHUB_ENV

      # - name: describe changeset
      #   if: inputs.CREATE_CHANGESET && github.event_name == 'pull_request' && env.CHANGESET_ARN
      #   run: |-
      #     echo "CHANGESET_DESCRIPTION<<EOF" >> $GITHUB_ENV
      #     aws cloudformation describe-change-set \
      #       --change-set-name ${{ env.CHANGESET_ARN }} \
      #       | jq '.Changes[].ResourceChange | {Operation: .Action, LogicalId: .LogicalResourceId, Type: .ResourceType, Replacement: .Replacement}' \
      #       >> $GITHUB_ENV
      #     echo "EOF" >> $GITHUB_ENV

      # - name: Comment on Pull Request
      #   uses: actions/github-script@v6
      #   if: inputs.CREATE_CHANGESET && github.event_name == 'pull_request' && env.CHANGESET_DESCRIPTION
      #   with:
      #     script: |
      #       const output = `## ${{ env.STACK_NAME_PREFIX }}${{ inputs.API_NAME }} changeset
      #       \`\`\`
      #       ${{ env.CHANGESET_DESCRIPTION }}
      #       \`\`\`
      #       *Pusher: @${{ github.actor }}*`;
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: output
      #       })

      - name: deploy
        if: inputs.DEPLOY
        run: |-
          aws cloudformation deploy \
            --no-fail-on-empty-changeset \
            --template-file ${{ inputs.TEMPLATE_FILE_NAME }} \
            --role-arn ${{ secrets.DEPLOY_ROLE }} \
            --s3-bucket ${{ secrets.TEMPLATE_BUCKET }} \
            --s3-prefix "${{ secrets.AWS_ACCOUNT_ID }}/${{ env.STACK_NAME_PREFIX }}${{ inputs.STACK_NAME }}-${{ env.STAGE_NAME }}" \
            --stack-name "${{ env.STACK_NAME_PREFIX }}${{ inputs.STACK_NAME }}" \
            --capabilities ${{ inputs.SAM_CAPABILITIES }} \
            --parameter-overrides StageName=${{ env.STAGE_NAME }}
