name: Called SAM

on:
  workflow_call:
    inputs:
      # dry-run
      CREATE_CHANGESET:
        required: true
        type: boolean
        default: false
      # execute
      DEPLOY:
        required: true
        type: boolean
        default: false

      # api
      API_NAME:
        required: true
        type: string

      # file
      TEMPLATE_FILE:
        required: false
        type: string
        default: template.yaml
      PARAMETER_FILE:
        required: false
        type: string
        default: parameters.txt

      # optional
      STACK_NAME_PREFIX:
        required: false
        type: string
        default: 'cicd-api-'
      AWS_REGION:
        required: false
        type: string
        default: ap-northeast-1
      CFN_CAPABILITIES:
        required: false
        type: string
        default: CAPABILITY_IAM
      PYTHON_VERSION:
        required: false
        type: string
        default: '3.9'

    secrets:
      ACTION_ROLE:
        required: true
      DEPLOY_ROLE:
        required: true
      TEMPLATE_BUCKET:
        required: true
      COGNITO_ARN_USER:
        required: true
      COGNITO_ARN_SHOP:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      URL:
        required: true


permissions: 
  contents: read
  id-token: write
  pull-requests: write


jobs:
  SAM:
    runs-on: ubuntu-latest
    if: inputs.CREATE_CHANGESET || inputs.DEPLOY
    timeout-minutes: 20
    environment:
      name: ${{ github.event.pull_request.base.ref || github.ref_name }}
    env:
      STACK_NAME: ${{ inputs.STACK_NAME_PREFIX }}${{ inputs.API_NAME }}
      # STAGE_NAME: ${{ github.event.pull_request.base.ref || github.ref_name }}
      STAGE_NAME: sandbox
    defaults:
      run:
        working-directory: api/${{ inputs.API_NAME }}
    steps:
      - uses: actions/checkout@v3

      # AWS settings
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ACTION_ROLE }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: cli version & id
        run: |-
          aws --version
          sam --version
          aws sts get-caller-identity

      # Build
      - name: sam build
        run: sam build --use-container --template-file ${{ inputs.TEMPLATE_FILE }}

      # Create & show changeset
      - name: create changeset
        id: create_changeset
        if: inputs.CREATE_CHANGESET
        run: |-
          sam deploy \
            --no-execute-changeset \
            --no-fail-on-empty-changeset \
            --role-arn ${{ secrets.DEPLOY_ROLE }} \
            --s3-bucket ${{ secrets.TEMPLATE_BUCKET }} \
            --s3-prefix "${{ secrets.AWS_ACCOUNT_ID }}/${{ env.STACK_NAME }}-${{ env.STAGE_NAME}}" \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities ${{ inputs.CFN_CAPABILITIES }} \
            --template-file ${{ inputs.TEMPLATE_FILE }} \
            --parameter-overrides `cat ${{ inputs.PARAMETER_FILE }} | \
              sed -E 's@^#.*$@@g' | \
              sed -E 's@^(StageName=).*$@@g' | \
              sed -E 's@^(BaseURL=).*$@@g' | \
              sed -E 's@^(LambdaRuntime=).*$@@g' | \
              sed -E 's@^(CognitoArnUser=).*$@@g' | \
              sed -E 's@^(CognitoArnShop=).*$@@g'` \
              StageName="${{ env.STAGE_NAME }}" \
              BaseURL="${{ secrets.URL }}" \
              LambdaRuntime="${{ inputs.PYTHON_VERSION }}" \
              CognitoArnUser="${{ secrets.COGNITO_ARN_USER }}" \
              CognitoArnShop="${{ secrets.COGNITO_ARN_SHOP }}" \
            > result.txt 2>&1
      
      - name: show create-changeset result
        if: inputs.CREATE_CHANGESET && always()
        run: |-
          cat result.txt

      - name: store create-changeset result
        if: inputs.CREATE_CHANGESET
        run: |-
          echo "CHANGESET_REPORT<<EOF" >> $GITHUB_ENV
          cat result.txt | sed -z 's@.*CloudFormation stack changeset\n\(.*\)\nChangeset created.*@\1@g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment on Pull Request
        uses: actions/github-script@v6
        if: inputs.CREATE_CHANGESET && github.event_name == 'pull_request'
        with:
          script: |
            const report = `${{ env.CHANGESET_REPORT }}`;
            const body = '## ${{ env.STACK_NAME }} changeset\n' +
              (report.match(/No changes to deploy./) ? '### No changes to deploy.\n' : ('```\n' + report + '\n```\n')) + 
              '*Pusher: @${{ github.actor }}*';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body,
            });

      # Deploy
      - name: sam deploy
        if: inputs.DEPLOY
        run: |-
          sam deploy \
            --force-upload \
            --no-confirm-changeset \
            --no-disable-rollback \
            --no-fail-on-empty-changeset \
            --role-arn ${{ secrets.DEPLOY_ROLE }} \
            --s3-bucket ${{ secrets.TEMPLATE_BUCKET }} \
            --s3-prefix "${{ secrets.AWS_ACCOUNT_ID }}/${{ env.STACK_NAME }}-${{ env.STAGE_NAME}}" \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities ${{ inputs.CFN_CAPABILITIES }} \
            --template-file ${{ inputs.TEMPLATE_FILE }} \
            --parameter-overrides `cat ${{ inputs.PARAMETER_FILE }} | \
              sed -E 's@^#.*$@@g' | \
              sed -E 's@^(StageName=).*$@@g' | \
              sed -E 's@^(BaseURL=).*$@@g' | \
              sed -E 's@^(LambdaRuntime=).*$@@g' | \
              sed -E 's@^(CognitoArnUser=).*$@@g' | \
              sed -E 's@^(CognitoArnShop=).*$@@g'` \
              StageName="${{ env.STAGE_NAME }}" \
              BaseURL="${{ secrets.URL }}" \
              LambdaRuntime="${{ inputs.PYTHON_VERSION }}" \
              CognitoArnUser="${{ secrets.COGNITO_ARN_USER }}" \
              CognitoArnShop="${{ secrets.COGNITO_ARN_SHOP }}"
