name: api/items

on:
  pull_request:
    types:
      - closed
    branches:
      - dev
      - stg
      - prd
    paths:
      - api/items/**
  workflow_dispatch:

jobs:
  sam-deploy:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/sam-deploy.yml
    with:
      API_NAME: items
      COGNITO_USER_POOL: user
    secrets: inherit