name: api-items

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [dev, stg, prd]
    paths:
      - api/items/**

jobs:
  sam-deploy:
    if: github.event.pull_request.merged == true || github.event_name != pull_request
    uses: ./.github/workflows/sam-deploy.yml
    with:
      API_NAME: items
      COGNITO_USER_POOL: user
    secrets: inherit