name: api-items

on:
  workflow_dispatch:
  push:
    branches: [dev, stg, prd]
    paths:
      - api/items/**

jobs:
  sam-deploy:
    uses: ./.github/workflows/sam-deploy.yml
    with:
      API_NAME: items
      COGNITO_USER_POOL: user
    secrets: inherit