name: api-items

on:
  workflow_dispatch:
    inputs:
      CREATE_CHANGESET:
        description: 'create changeset'
        required: false
        type: boolean
        default: false
      DEPLOY:
        description: 'deploy'
        required: false
        type: boolean
        default: false
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches: [dev, stg, prd]
    paths:
      - api/items/**
  push:
    branches: [sandbox]
    paths:
      - api/items/**

jobs:
  deploy:
    uses: ./.github/workflows/called-sam-deploy.yml
    with:
      API_NAME: items
      COGNITO_USER_POOL: user
      CREATE_CHANGESET:
        ${{ github.event.pull_request.state == 'open' || inputs.CREATE_CHANGESET }}
      DEPLOY:
        ${{ github.event.pull_request.merged || inputs.DEPLOY }}
    secrets: inherit