name: items
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: echo ${{ env.GITHUB_ACTION }}
      - run: ls
      - run: ls
        working-directory: api/${{ env.GITHUB_ACTION }}
