name: test-sam

on:
  workflow_dispatch:
    inputs:
      CREATE_CHANGESET:
        description: 'create changeset'
        required: false
        type: boolean
        default: false
      DEPLOY:
        description: 'deploy'
        required: false
        type: boolean
        default: false
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths:
      - api/items/**

jobs:
  CICD:
    with:
      API_NAME: items
      COGNITO_USER_POOL: user
      
      CREATE_CHANGESET:
        ${{ github.event.pull_request.state == 'open' || inputs.CREATE_CHANGESET == true }}
      DEPLOY:
        ${{ github.event.pull_request.merged || inputs.DEPLOY == true }}
    secrets: inherit
    uses: ./.github/workflows/called-sam-deploy.yml

