name: reuse test
on:
  push:
    branches:
      - develop
    paths:
      - api/items/**
  workflow_dispatch:

# env:
#   API_NAME: items
#   COGNITO_USER_POOL: user

jobs:
  sam-deploy:
    uses: ./.github/workflows/sam-deploy.yml
    with:
      API_NAME: items
      COGNITO_USER_POOL: user
    secrets: inherit