name: test-cf

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [dev, stg, prd]
    paths:
      - iac/test-cfn/**

jobs:
  cf-test:
    uses: ./.github/workflows/called-cfn-deploy.yml
    with:
      STACK_NAME: cloudfront-test
      TEMPLATE_FILE_NAME: test.yml
      WORKING_DIRECTORY: iac/test_cfn
    secrets: inherit
