name: items
on:
  workflow_dispatch:
  push:

env:
  API_NAME: items

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: api/${{ env.API_NAME }}
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ github.action }}
      - run: ls
